// <auto-generated />
using Anaokulu.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anaokulu.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext1))]
    [Migration("20230416230307_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Dersler", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DersAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgretmenID")
                        .HasColumnType("int");

                    b.Property<int>("YasGrubu")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("DersID");

                    b.HasIndex("OgretmenID");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Etkinlikler", b =>
                {
                    b.Property<int>("EtkinlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EtkinlikAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YasGrubu")
                        .HasColumnType("int");

                    b.HasKey("EtkinlikID");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciNo");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Ogrenciler", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OgrenciAdsoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgretmenID")
                        .HasColumnType("int");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("OgrenciID");

                    b.HasIndex("OgretmenID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Ogretmenler", b =>
                {
                    b.Property<int>("OgretmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgretmenAdi")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("OgretmenSoyadi")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("OgretmenID");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Dersler", b =>
                {
                    b.HasOne("AnaokuluKatmanli.Model.Models.Ogretmenler", "Ogretmenler")
                        .WithMany("Dersler")
                        .HasForeignKey("OgretmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogretmenler");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Ogrenciler", b =>
                {
                    b.HasOne("AnaokuluKatmanli.Model.Models.Ogretmenler", "Ogretmenler")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("OgretmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogretmenler");
                });

            modelBuilder.Entity("AnaokuluKatmanli.Model.Models.Ogretmenler", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
